# spring.application.name=auth-service
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    exchange: ${EXCHANGE_RABBIT}
    name_queue: ${NAME_QUEUE_AUTH}
    host: ${RABBITMQ_HOST}
    port: ${PORTS_CLIENT_RABBIT_EXPOSE}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    event_one: ${EVENT_ONE}
    event_two: ${EVENT_TWO}

jwt:
  secret: ${JWT_SECRET:miClaveSuperSecreta}

data_rabbit:
  event_one: ${EVENT_ONE}
  event_two: ${EVENT_TWO}
  event_three: ${EVENT_THREE}

auth:
  service:
    email: ${AUTH_SERVICE_EMAIL}
    password: ${AUTH_SERVICE_PASSWORD}
    role: ${AUTH_SERVICE_ROLE}
