pipeline {
  agent {
    docker {
      image 'golang:1.26-alpine'
      args '-v /root/go/pkg:/root/go/pkg --network challenges-microservices_microservices-network '
    }
  }

  environment {
    SONAR_TOKEN = credentials('sonar-token')
  }

  stages {
    stage('Checkout') {
      steps { echo '📥 Código obtenido' }
    }

stage('Build') {
    steps {

        dir('department_backend') {

            sh '''
                export PATH=$PATH:$(go env GOPATH)/bin

                go install github.com/swaggo/swag/cmd/swag@latest

                swag init -g cmd/app/main.go

                go build ./...
            '''
        }
    }
}

stage('Test') {
    steps {

        dir('department_backend') {

            sh '''
                go test ./... -coverprofile=coverage.out
                go tool cover -func=coverage.out
            '''
        }
    }
}

stage('SonarQube') {
    steps {

        dir('department_backend') {

            sh '''
                apk add --no-cache unzip wget openjdk17-jre

                export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
                export PATH=$JAVA_HOME/bin:$PATH

                wget -q https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006.zip

                unzip -o sonar-scanner-cli-5.0.1.3006.zip

                ./sonar-scanner-5.0.1.3006/bin/sonar-scanner \
                  -Dsonar.projectKey=go-service \
                  -Dsonar.sources=. \
                  -Dsonar.go.coverage.reportPaths=coverage.out \
                  -Dsonar.host.url=http://sonarqube:9000 \
                  -Dsonar.token=$SONAR_TOKEN
            '''
        }
    }
}

stage('Quality Gate') {
    steps {

        timeout(time: 5, unit: 'MINUTES') {
            waitForQualityGate abortPipeline: true
        }
    }
}

    stage('Package') {
      steps {
        script {
          def tag = "${env.BUILD_NUMBER}"
          sh "docker build -t localhost:5000/:${tag}  -t localhost:5000/:latest  ./department_backend"
          sh "docker push localhost:5000/:${tag}"
        }
      }
    }
  }

  post {
    success { echo '✅ Pipeline Go completado' }
    failure { echo '❌ Pipeline Go falló' }
  }
}
