pipeline {
  agent {
    docker {
      image 'node:20-alpine'
      args '-v /root/.npm:/root/.npm'
    }
  }

  environment {
    SONAR_TOKEN = credentials('sonar-token')
  }

  stages {
    stage('Checkout') {
      steps { echo '📥 Código obtenido' }
    }

    stage('Build') {
      steps {
        dir('microservice-logs') {
          sh 'npm ci'
        }
      }
    }

    stage('Test') {
      steps {
        dir('microservice-logs') {
          sh 'npx nyc --reporter=lcov npm test'
          // genera coverage/lcov.info
        }
      }
    }

    stage('SonarQube') {
      steps {
        dir('microservice-logs') {
          withSonarQubeEnv('SonarQube') {
          sh """
            npx sonar-scanner \
              -Dsonar.projectKey=logs-service \
              -Dsonar.sources=src \
              -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info 
          """
        }
      }
    }

    stage('Quality Gate') {
      steps {
        timeout(time: 5, unit: 'MINUTES') {
          waitForQualityGate abortPipeline: true
        }
      }
    }

    stage('Package') {
      steps {
        script {
          def tag = "${env.BUILD_NUMBER}"
          sh "docker build -t localhost:5000/logs-service:${tag} -t localhost:5000/logs-service:latest ./microservice-logs"
          sh "docker push localhost:5000/logs-service:${tag}"
        }
      }
    }
  }

  post {
    success { echo '✅ Pipeline Logs completado' }
    failure { echo '❌ Pipeline Logs falló' }
  }
}
