pipeline {
  agent {
    docker {
      image 'node:20-alpine'
      args '-v /root/.npm:/root/.npm --network challenges-microservices_microservices-network'
    }
  }

  environment {
    SONAR_TOKEN = credentials('sonar-token')
  }

  stages {
    stage('Checkout') {
      steps { echo '📥 Código obtenido' }
    }

    stage('Build') {
      steps {
        dir('microservice-logs') {
          sh 'npm ci'
        }
      }
    }

    stage('Test') {
      steps {
        dir('microservice-logs') {
          sh 'npx nyc --reporter=lcov npm test'
          // genera coverage/lcov.info
        }
      }
    }

stage('SonarQube') {
  steps {
    dir('microservice-logs') {

      withSonarQubeEnv('SonarQube') {

        sh '''
          apk add --no-cache openjdk17-jre wget unzip

          wget -q https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006.zip

          unzip -oq sonar-scanner-cli-5.0.1.3006.zip

          export PATH=$PATH:$(pwd)/sonar-scanner-5.0.1.3006/bin

          sonar-scanner \
            -Dsonar.projectKey=logs-service \
            -Dsonar.sources=src \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        '''
      }
    }
  }
}

    // stage('Quality Gate') {
    //   steps {
    //     timeout(time: 15, unit: 'MINUTES') {
    //       waitForQualityGate abortPipeline: true
    //     }
    //   }
    // }

    stage('Package') {
      steps {
        script {
          def tag = "${env.BUILD_NUMBER}"
          sh "docker build -t localhost:5000/logs-service:${tag} -t localhost:5000/logs-service:latest ./microservice-logs"
          sh "docker push localhost:5000/logs-service:${tag}"
        }
      }
    }
  }

  post {
    success { echo '✅ Pipeline Logs completado' }
    failure { echo '❌ Pipeline Logs falló' }
  }
}
