pipeline {
  agent {
    docker {
      image 'node:20-alpine'
      args '-v /root/.npm:/root/.npm'
    }
  }

  environment {
    SONAR_TOKEN = credentials('sonar-token')
  }

  stages {
    stage('Checkout') {
      steps { echo '📥 Código obtenido' }
    }

    stage('Build') {
      steps {
        dir('microservicio-node') {
          sh 'npm ci'
        }
      }
    }

    stage('Test') {
      steps {
        dir('microservicio-node') {
          sh 'npx nyc --reporter=lcov npm test'
          // genera coverage/lcov.info
        }
      }
    }

    stage('SonarQube') {
      steps {
        dir('microservicio-node') {
          sh """
            npx sonar-scanner \
              -Dsonar.projectKey=node-service \
              -Dsonar.sources=src \
              -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
              -Dsonar.host.url=http://sonarqube:9000 \
              -Dsonar.token=${SONAR_TOKEN}
          """
        }
      }
    }

    stage('Quality Gate') {
      steps {
        timeout(time: 5, unit: 'MINUTES') {
          waitForQualityGate abortPipeline: true
        }
      }
    }

    stage('Package') {
      steps {
        script {
          def tag = "${env.BUILD_NUMBER}"
          sh "docker build -t localhost:5000/node-service:${tag} -t localhost:5000/node-service:latest ./microservicio-node"
          sh "docker push localhost:5000/node-service:${tag}"
        }
      }
    }
  }

  post {
    success { echo '✅ Pipeline Node.js completado' }
    failure { echo '❌ Pipeline Node.js falló' }
  }
}
