pipeline {
  agent {
    docker {
      image 'maven:3.9-eclipse-temurin-21'
      args '''
            -v /root/.m2:/root/.m2
            -v /var/run/docker.sock:/var/run/docker.sock
            --network challenges-microservices_microservices-network
            '''
    }
  }

  environment {
    SONAR_TOKEN = credentials('sonar-token')
  }

  stages {
    stage('Checkout') {
      steps {
        echo '📥 Código obtenido'
      }
    }

    stage('Build') {
      steps {
        dir('auth-service') {
          sh 'mvn clean compile -DskipTests'
        }
      }
    }

    stage('Test') {
      steps {
        dir('auth-service') {
          sh 'mvn test jacocoTestReport'
        }
      }
      post {
        always {
          junit 'auth-service/target/surefire-reports/*.xml'
        }
      }
    }

    stage('SonarQube') {
      steps {
        dir('auth-service') {
          withSonarQubeEnv('SonarQube') {
            sh """
              mvn sonar:sonar \
                -Dsonar.projectKey=auth-service \
                -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
            """
          }
        }
      }
    }

    // stage('Quality Gate') {
    //   steps {
    //     timeout(time: 5, unit: 'MINUTES') {
    //       waitForQualityGate abortPipeline: true
    //     }
    //   }
    // }

    stage('Package') {
      steps {
        script {
          def tag = "${env.BUILD_NUMBER}"
          sh """
            apt-get update
            apt-get install -y docker.io

            docker build \
              -t localhost:5000/auth-service:${tag} \
              -t localhost:5000/auth-service:latest \
              ./auth-service

            docker push localhost:5000/auth-service:${tag}
            docker push localhost:5000/auth-service:latest
          """
        }
      }
    }
  }

  post {
    success { echo '✅ Pipeline auth-service completado' }
    failure { echo '❌ Pipeline auth-service falló' }
  }
}
