pipeline {
  agent {
    docker {
      image 'gradle:8.10.2-jdk21'
      // args '-v /root/.gradle:/root/.gradle'  // cache de dependencias
      args '''
            -v /root/.gradle:/root/.gradle
            -v /var/run/docker.sock:/var/run/docker.sock
            --network challenges-microservices_microservices-network
            '''
    }
  }

  environment {
    SONAR_TOKEN = credentials('sonar-token')
  }

  stages {
    stage('Checkout') {
      steps {
        echo '📥 Código obtenido'
      }
    }

    stage('Build') {
      steps {
        dir('employee-backend') {
          sh 'chmod +x ./gradlew'
          sh './gradlew clean classes -x test'
        }
      }
    }

    stage('Test') {
      steps {
        dir('employee-backend') {
          sh './gradlew test jacocoTestReport'
        }
      }
      post {
        always {
          junit 'employee-backend/build/test-results/test/*.xml'
        }
      }
    }


    stage('SonarQube') {
      steps {

        dir('employee-backend') {

          withSonarQubeEnv('SonarQube') {

            sh """
              ./gradlew sonar \
                -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
            """
          }
        }
      }
}

    // stage('Quality Gate') {
    //   steps {
    //     timeout(time: 5, unit: 'MINUTES') {
    //       waitForQualityGate abortPipeline: true
    //     }
    //   }
    // }

    stage('Package') {
      steps {
        script {
          def tag = "${env.BUILD_NUMBER}"
                sh """
                    apt-get update
                    apt-get install -y docker.io

                    docker build \
                      -t localhost:5000/employee-backend:${tag} \
                      -t localhost:5000/employee-backend:latest \
                      ./employee-backend

                    docker push localhost:5000/employee-backend:${tag}

                    docker push localhost:5000/employee-backend:latest
                  """        }
      }
    }
  }

  post {
    success { echo '✅ Pipeline employee-backend completado' }
    failure { echo '❌ Pipeline employee-backend falló' }
  }
}
